### ISSUE TITLE
how to do postprocessing

### ISSUE THREAD

**Issue by luohao123** [ZwwWayne/K-Net#10]
the mask seems not accurate, for a same object, it still could be generate multiple masks which is not good, how to postprocessing supress them?

**Comment by ZwwWayne** [comment]
This is a common issue for all detectors. You can just set a threshold to suppress them. For methods like DETR/K-Net, we usually just output what the network output and it works.

**Comment by luohao123** [comment]
@ZwwWayne I found original code outputs fixed 100 objects. I fixed by using a threshold.
