### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by ztt0821** [ZwwWayne/K-Net#11]
Hi, I have a little question about training. I am using mmdetection architecture to train other models. But I didn't use Slurm to train the model . I am using the following command
"bash ./tools/dist_train.sh \
    ${CONFIG_FILE} \
    ${GPU_NUM} \
    [optional arguments]" 

May I ask could you give one example to show how to train the model use "bash ./tools/dist_train.sh". Thank you very much.

**Comment by xiehousen** [comment]
I put this code into MMDETECTION, that's worked.

**Comment by ztt0821** [comment]
Thank you very much for your reply. Could you share the link of the code in mmdetection. Because I didn't find the K-net in mmdetection https://github.com/open-mmlab/mmdetection

**Comment by ZwwWayne** [comment]
Then you can modify the script as 
```
#!/usr/bin/env bash

set -x

TASK=$1
CONFIG=$2
WORK_DIR=$3
GPUS=${GPUS:-8}
PY_ARGS=${@:5}

PYTHONPATH='.':$PYTHONPATH mim train $TASK $CONFIG \
    --launcher pytorch -G $GPUS \
    --work-dir $WORK_DIR \
    $PY_ARGS
```

**Comment by ZwwWayne** [comment]
See more usages about training command in https://github.com/open-mmlab/mim#command
