### ISSUE TITLE
KeyError: 'KNet is not in the models registry' when runing 'train.py'

### ISSUE THREAD

**Issue by lifuguan** [ZwwWayne/K-Net#18]
## Description
I directly use your repo as my workspace, the directory tree is shown below(mmdetection has been installed by conda):
![image](https://user-images.githubusercontent.com/17793134/145971756-40032d06-ac0d-4244-9fcc-0636c5b8dcbe.png)
Then I run the following command which is pretty well when using builtin model:
```bash
sh ./tools/mim_slurm_test.sh $PARTITION mmdet $CONFIG $CHECKPOINT --eval segm
```
## Problem
It shows `KNet` doesn't register:
```bash
KeyError: 'KNet is not in the models registry'
```

## Attempt
Repo [mim-example](https://github.com/open-mmlab/mim-example/tree/master/swin_transformer#step-3-use-swin-transformer-through-config) mentions that **we can simply use the config and the build function**. However, the following sample code is no used in the repo, which confused me a lot.
```python 
module_cfg = dict(type='mmcv.SwinTransformer')
module = build_backbone(module_cfg)
```

### How can I fix this problem? Any help will be appreciated.

**Comment by ZwwWayne** [comment]
Which version of mmdetection are you using? Do you have trouble in training the model?
The config works for me.
KNet is not in the models registry usually means the file implementing K-Net is not correctly imported, which has no relation with the build function.

**Comment by lifuguan** [comment]
> Which version of mmdetection are you using? Do you have trouble in training the model? The config works for me. KNet is not in the models registry usually means the file implementing K-Net is not correctly imported, which has no relation with the build function.
Thanks for your sincere reply. I've successfully trained KNet after correcting my config error(KNet been imported on other mm toolbox rather than mmdet).
