### ISSUE TITLE
About your semantic segmentation？

### ISSUE THREAD

**Issue by EricStarer** [ZwwWayne/K-Net#19]
In your code of semantic segmentation， I noticed that you give a softmax operation for input mask in your kernel update head. I wonder whether it means that the input mask need at least two channels, and if my network only output 1 channel mask, how can I modify my network so that your idea can keep work?

**Comment by ZwwWayne** [comment]
You may make it a 2 channel mask, where the first one indicates foreground and the second one indicates the background.
