### ISSUE TITLE
About experiments setting

### ISSUE THREAD

**Issue by NickChang97** [ZwwWayne/K-Net#23]
Hi, really thanks for sharing your fantastic work! However, I have something puzzled about the implementation details in Sectrion 4. Why mult-scale training with a longer schedule used  for fair comparisons ?

**Comment by ZwwWayne** [comment]
The original context is: When comparing with other frameworks, we use multi-scale training with a longer schedule (36 epochs) for fair comparison. Because other methods usually report a high performance with multi-scale training and longer schedule.
