### ISSUE TITLE
IoU are all Nan, training the both deeplabv3 and swin-t on ADE20K dataset, why?

### ISSUE THREAD

**Issue by Mollylulu** [ZwwWayne/K-Net#9]
![image](https://user-images.githubusercontent.com/26273127/140593081-dac649d2-c4bd-4433-8eaf-200d07df45c1.png)
through out the whole training, these metrics are all Nan, neither deeplabv3 nor swin-t, I just use the config given in this repo and do not change. except  SynBN would cause error and I change it into normal BN.
hope you could help, thanks!

**Comment by ZwwWayne** [comment]
Changing it to normal BN will decrease the performance of segmentation models.
Could you post the command you for us to repdocue?

**Comment by Mollylulu** [comment]
sorry for late reply. I run with :
1. for deeplab:
`PYTHONPATH='.':/home/xxx/anaconda3/envs/knet/bin/python3 MMCV_HOME=/home/xxx mim train mmseg /home/xxx/git/K-Net/configs/seg/knet/knet_s3_deeplabv3_r50-d8_80k_adamw_ade20k.py --gpus 1 --work-dir /home/xxx/git/K-Net/results --resume-from /home/xxx/git/K-Net/results/latest.pth `
2. for swin-t:
`PYTHONPATH='.':/home/xxx/anaconda3/envs/smore/bin/python3 MMCV_HOME=/home/xxx mim train mmseg /home/xxx/git/K-Net/configs/seg/knet/knet_s3_upernet_swin-t_80k_adamw_ade20k.py --gpus 1 --work-dir /home/xxx/git/K-Net/swin_results`
@ZwwWayne

**Comment by ZwwWayne** [comment]
It seems you only use 1 GPU. You should decrease the learning rate accordingly.
